spring:
  application:
    name: user-service  # Service name
  datasource:
    url: jdbc:postgresql://172.16.230.59:5432/health_care?currentSchema=users
    username: superadmin
    password: admin@123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
#  config:
#    import: id-generator.yml

management:
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8082
  shutdown: graceful # Service port

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost  # Optional: specify the hostname
    prefer-ip-address: true

http:
  header:
    auth: Authorization

host:
  url: http://localhost:8000