spring:
  application:
    name: user-service  # Service name
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: tasin
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true


management:
  endpoint:
    health:
      probes:
        enabled: true

server:
  port: 8082
  shutdown: graceful # Service port

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # Eureka server URL
    fetch-registry: true
    register-with-eureka: true
  instance:
    hostname: localhost  # Optional: specify the hostname
    prefer-ip-address: true

