unique.id.patient.prefix=PT
unique.id.admin.prefix=AD
unique.id.doctor.prefix=DC
unique.id.checker.macker=MC
unique.id.appointment.prefix=AP


bmdc_csrf_cookie = bmdckyc_csrf_cookie
bmdc_session_cookie = bmdckyc_sessions
bmdc_reg_student = 1
bmdc_action_key = eU3sujCZPvwo
bmdc_action_flag = 1