version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.2
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.2.2
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092  # Advertise the container name as Kafka address
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092          # Expose Kafka on all interfaces of the container
      KAFKA_LISTENER_SECURITY_PROTOCOL: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  kafka-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kafka-service
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker
      HEALTHCARE_KAFKA_BOOTSTRAP_SERVERS: kafka:9092  # Point to Kafka container using its service name
    depends_on:
      - kafka
    # Optional: Wait for Kafka to be fully up before starting your service
    entrypoint: ["sh", "-c", "while ! nc -z kafka 9092; do sleep 1; done; java -jar /app/kafka-service.jar"]
